CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS KM_NODE (
  NODE_ID VARCHAR(255) PRIMARY KEY,
  NODE_URI VARCHAR(255),
  NODE_NAME VARCHAR(255),
  IS_ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS KM_SCHEDULER_CONF (
  TRIGGER_NAME VARCHAR(64) PRIMARY KEY,
  SCHE_NAME VARCHAR(64),
  IS_RUNNING BOOLEAN,
  IS_ACTIVE BOOLEAN,
  CRON_EXPR VARCHAR(32),
  LAST_BEGIN_RUN_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KM_MAIN_STAT (
  THREAD_KEY VARCHAR(255) PRIMARY KEY,
  FK_NODE_ID VARCHAR(255),
  BEGIN_TIME TIMESTAMP,
  END_TIME TIMESTAMP,
  YEAR INTEGER,
  MONTH INTEGER,
  DAY INTEGER,
  HOUR INTEGER
);

CREATE TABLE IF NOT EXISTS KM_HTTP_DETAILS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  VERSION INTEGER,
  THREAD_KEY VARCHAR(255),
  NODE_ID VARCHAR(255),
  BEGIN_TIME TIMESTAMP,
  TIME_CONSUME BIGINT,
  IP VARCHAR(255),
  URI VARCHAR(255),
  REFERER VARCHAR(255),
  PRINCIPAL VARCHAR(255),
  PARAMETERS CLOB
);

CREATE TABLE IF NOT EXISTS KM_METHOD_DETAILS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  VERSION INTEGER,
  THREAD_KEY VARCHAR(255),
  NODE_ID VARCHAR(255),
  BEGIN_TIME TIMESTAMP,
  TIME_CONSUME BIGINT,
  METHOD VARCHAR(255),
  IS_SUCCESSED BOOLEAN,
  STACK_DETAILS CLOB
);

CREATE TABLE IF NOT EXISTS KM_JDBC_DETAILS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  VERSION INTEGER,
  THREAD_KEY VARCHAR(255),
  NODE_ID VARCHAR(255),
  BEGIN_TIME TIMESTAMP,
  TIME_CONSUME BIGINT,
  CONN_OPEN_COUNT INTEGER,
  STMT_CREATE_COUNT INTEGER,
  PSTMT_CREATE_COUNT INTEGER,
  CONN_CLOSE_COUNT INTEGER,
  STMT_CLOSE_COUNT INTEGER,
  PSTMT_CLOSE_COUNT INTEGER,
  SQLS CLOB
);

CREATE TABLE IF NOT EXISTS KM_JDBC_CONN_DETAILS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  VERSION INTEGER,
  THREAD_KEY VARCHAR(255),
  NODE_ID VARCHAR(255),
  BEGIN_TIME TIMESTAMP,
  TIME_CONSUME BIGINT,
  IS_CLOSED BOOLEAN
);

CREATE TABLE IF NOT EXISTS KM_STMT_DETAILS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  VERSION INTEGER,
  FK_CONN_ID BIGINT,
  BEGIN_TIME TIMESTAMP,
  TIME_CONSUME BIGINT,
  EXECUTE_SQL VARCHAR(1000),
  DML_TYPE VARCHAR(255),
  IS_CLOSED BOOLEAN
);
